# Generated by Django 4.2.7 on 2023-12-03 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DANI_NAIL_ART', '0002_cita_contactmessage_galeria_promociones_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='custom_user_permissions',
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='your_default_value', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='precio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
