# Generated by Django 4.2.7 on 2023-12-03 05:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DANI_NAIL_ART', '0003_remove_customuser_custom_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, max_length=10, unique=True),
        ),
    ]
